import type { Metadata } from "next";
import Link from "next/link";
import { Icon } from "@iconify/react";
import { Button } from "@/components/ui/button";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Input } from "@/components/ui/input";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { SIDENAV_ITEMS } from "@/menu";
import { ScrollArea } from "@/components/ui/scroll-area";
import { MenuItem } from "@/components/layouts/side-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className=" min-h-screen w-full absolute">
      <div className="hidden border-r bg-muted/40 md:block fixed h-full w-72">
        <div className="flex h-full max-h-screen flex-col gap-2">
          <div className="flex h-14 items-center border-b px-4 lg:h-[60px] lg:px-6">
            <Link href="/" className="flex items-center gap-2 font-semibold">
              <Icon icon="lucide:package-2" className="h-6 w-6" />
              <span className="">E-PKK</span>
            </Link>
            <Button variant="outline" size="icon" className="ml-auto h-8 w-8">
              <Icon icon="lucide:bell" className="h-4 w-4" />
              <span className="sr-only">Toggle notifications</span>
            </Button>
          </div>
          <div className="flex-1">
            <nav className="grid items-start px-2 text-sm font-medium lg:px-4">
              {SIDENAV_ITEMS.map((item, idx) => {
                return <MenuItem key={idx} item={item} />;
              })}
            </nav>
          </div>
          <div className="mt-auto p-4">
            <Card x-chunk="dashboard-02-chunk-0">
              <CardHeader className="p-2 pt-0 md:p-4">
                <CardTitle>Butuh bantuan?</CardTitle>
                <CardDescription>
                  Dapatkan buku panduan E-Pkk dibawah ini
                </CardDescription>
              </CardHeader>
              <CardContent className="p-2 pt-0 md:p-4 md:pt-0">
                <Button size="sm" className="w-full">
                  Download
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
      <div className="flex flex-col w-full md:pl-72">
        <header className="flex h-14 items-center gap-4 border-b bg-muted/40 px-4 lg:h-[60px] lg:px-6">
          <Sheet>
            <SheetTrigger asChild>
              <Button
                variant="outline"
                size="icon"
                className="shrink-0 md:hidden"
              >
                <Icon icon="mdi:menu" width="24" height="24" />
                <span className="sr-only">Toggle navigation menu</span>
              </Button>
            </SheetTrigger>
            <SheetContent side="left" className="flex flex-col ">
              <ScrollArea>
                <Link
                  href="#"
                  className="flex items-center gap-2 text-lg font-semibold"
                >
                  {/* <Package2 className="h-6 w-6" /> */}
                  <span className="sr-only">E-PKK</span>
                </Link>
                {SIDENAV_ITEMS.map((item, idx) => {
                  return <MenuItem key={idx} item={item} />;
                })}
              </ScrollArea>
              {/* <nav className="grid gap-2  text-lg font-medium">
                <Link
                  href="#"
                  className="flex items-center gap-2 text-lg font-semibold"
                >
                  <span className="sr-only">E-PKK</span>
                </Link>
                {SIDENAV_ITEMS.map((item, idx) => {
                  return <MenuItem key={idx} item={item} />;
                })}
              </nav> */}
              <div className="mt-auto">
                <Card x-chunk="dashboard-02-chunk-0">
                  <CardHeader className="p-2 pt-0 md:p-4">
                    <CardTitle>Butuh bantuan?</CardTitle>
                    <CardDescription>
                      Dapatkan buku panduan E-Pkk dibawah ini
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="p-2 pt-0 md:p-4 md:pt-0">
                    <Button size="sm" className="w-full">
                      Download
                    </Button>
                  </CardContent>
                </Card>
              </div>
            </SheetContent>
          </Sheet>
          <div className="w-full flex-1"></div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="secondary" size="icon" className="rounded-full">
                {/* <CircleUser className="h-5 w-5" /> */}
                <Icon icon="lucide:circle-user" className="h-4 w-4" />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Support</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </header>
        <main className="flex  gap-4 p-4 lg:gap-6 lg:p-6">
          <div
            className=" rounded-lg border border-dashed shadow-sm p-4  w-full"
            x-chunk="dashboard-02-chunk-1"
          >
            {children}
          </div>
        </main>
      </div>
    </div>
  );
}
